global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [
        'node_exporter_1:9100',
        'node_exporter_2:9100'
      ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
